### ISSUE TITLE
Does not seem to work on Mac

### ISSUE THREAD

**Issue by vansh1sh** [vmalyi/adb_android#38]
*** Executing adb push /tmp/file.txt /data/media/0 command

Traceback (most recent call last):
  File "/Users/apple/Desktop/check.py", line 7, in <module>
    adb_android.push('/tmp/file.txt', '/data/media/0')
  File "/usr/local/lib/python2.7/site-packages/adb_android/adb_android.py", line 58, in push
    return _exec_command(adb_full_cmd)
  File "/usr/local/lib/python2.7/site-packages/adb_android/adb_android.py", line 194, in _exec_command
    output = check_output(final_adb_cmd, stderr=t)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by vmalyi** [comment]
Please provide more details if the issue is still actual
